### ISSUE TITLE
Icecat classificationstore js file is impactig native classification store functionality

### ISSUE THREAD

**Issue by praveenjha2112** [IcecatNV/Icecat-Integration#12]
We have integrat the Icecate version 3.0 in our project .
![image](https://user-images.githubusercontent.com/112381479/208616141-b78aee60-1da5-4b8d-b869-e0b2b7a6758c.png)

above file is impacting the native classification store functionality

it disabled it 
![image](https://user-images.githubusercontent.com/112381479/208616467-95f76bf2-2e1f-4dc8-b24b-47bcff9c9bf1.png)

**Comment by IcecatNV** [comment]
Hi Praveen,

Thank you for reporting the issue. (and for suggesting the work around).

**Comment by praveenjha2112** [comment]
Hi @IcecatNV 
Please suggest us a workaround for this issue as we have implemented icecat in one of our projects and facing this issue

**Comment by AndrejBykadorov** [comment]
Hello,

we are facing the same issue. After 3.0.0 installation, all the data from our existing Classification store are not visible in the UI. 
![image](https://user-images.githubusercontent.com/49982277/213657887-7f44169a-ae48-471d-b4d5-19a0f4de3a3c.png)

Can you give as some estimate when the issue will be fixed?

**Comment by IcecatNV** [comment]
Hi,

We are working on this, will let you know by end of this week.

**Comment by IcecatNV** [comment]
Hi @AndrejBykadorov 

We have fixed the issue and it will now not affect other store classifications (it will only impact the Icecat classification) and released a new V4.0.0 version. The V4 will work on Pimcore version 10.5.* 

Please test and confirm once the issue has been resolved at your end so that then I will close this issue.
